---
linters:
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  MergeableSelector:
    enabled: false
  NestingDepth:
    enabled: false
  PropertySortOrder:
    enabled: false
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
  UnnecessaryParentReference:
    enabled: false
  UrlQuotes:
    enabled: false
