#                                                                        #
# Settings for the Production context                                    #
#                                                                        #

TYPO3:
  Neos:
    typoScript:
      enableObjectTreeCache: TRUE
